### ISSUE TITLE
Roadmap vendredi 24

### ISSUE THREAD

**Issue by sylvain-reynaud** [polyxia-org/polyxia#18]
- [x] CLI pour builder le rootfs a partir du code utilisateur @croumegous @thomasgouveia 
- [x] upload du rootfs @croumegous @thomasgouveia 
- [x] (riklet) download le rootfs @croumegous @thomasgouveia 
- [ ] réseau dans rik @AlexandreBrg 
          * #17 
          * #20
- [x] exposition des functions @kalil-pelissier  
- [ ] avoir la capacité de savoir combien de temps [création de l'instance -> invocation] @AlexandreBrg
          * #19 
- [x] documenter (écrire les readme des repos + getting started pour dev et pour run, schéma) @JeremyLARDENOIS 

next step:
- [ ] (à faire apres UC10) consolider l'existant (ajouter tests e2e et unitaires, ux)
